#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HUB_SCRIPT="$ROOT_DIR/.agents/skills/vibe-hub/scripts/run.sh"

[[ -x "$HUB_SCRIPT" ]] || { echo "missing executable script: $HUB_SCRIPT"; exit 1; }

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

work_dir="$tmp_dir/work"
mkdir -p "$work_dir"
cp -R "$ROOT_DIR/bootstrap/assets"/. "$work_dir"/
cp -R "$ROOT_DIR/.agents" "$work_dir"/

mock_bin="$tmp_dir/mock-codex"
mkdir -p "$mock_bin"
cat > "$mock_bin/codex" <<'MOCK'
#!/usr/bin/env bash
if [[ "$1" == "execpolicy" && "$2" == "check" && "$3" == "--help" ]]; then
  echo "Usage: codex execpolicy check [OPTIONS] --rules <PATH> <COMMAND>..."
  exit 0
fi
if [[ "$1" == "execpolicy" && "$2" == "check" ]]; then
  echo '{"decision":"allow"}'
  exit 0
fi
exit 1
MOCK
chmod +x "$mock_bin/codex"

assert_has_step_report() {
  local file="$1"
  grep -q '\[step-report\]' "$file" || { echo "missing step-report in $file"; exit 1; }
  grep -q '^- NEXT_ACTION: ' "$file" || { echo "missing NEXT_ACTION in $file"; exit 1; }
}

pushd "$work_dir" >/dev/null

if PATH="$mock_bin:/usr/bin:/bin" bash .agents/skills/vibe-hub/scripts/run.sh unknown >"$tmp_dir/unknown.out" 2>&1; then
  echo "expected unknown command to fail"
  exit 1
fi
assert_has_step_report "$tmp_dir/unknown.out"

PATH="$mock_bin:/usr/bin:/bin" bash .agents/skills/vibe-hub/scripts/run.sh start \
  --goal "验证 hub 单入口路由" \
  --task-type feature \
  --work-type full \
  --spec-id SPEC-0097-hub > "$tmp_dir/start.out"
assert_has_step_report "$tmp_dir/start.out"
[[ -f docs/status/blackbox-session.md ]] || { echo "missing blackbox-session after hub start"; exit 1; }
[[ -f docs/status/current-task.md ]] || { echo "missing current-task after hub start"; exit 1; }

PATH="$mock_bin:/usr/bin:/bin" bash .agents/skills/vibe-hub/scripts/run.sh status > "$tmp_dir/status.out"
assert_has_step_report "$tmp_dir/status.out"
grep -q '\[blackbox-card\]' "$tmp_dir/status.out" || { echo "status should include blackbox card"; exit 1; }

PATH="$mock_bin:/usr/bin:/bin" bash .agents/skills/vibe-hub/scripts/run.sh task-pack \
  --spec-id SPEC-0097-hub-2 \
  --task-type feature \
  --current-role Dev \
  --next-role QA > "$tmp_dir/task-pack.out"
assert_has_step_report "$tmp_dir/task-pack.out"
[[ -f docs/specs/SPEC-0097-hub-2.md ]] || { echo "missing spec generated by hub task-pack"; exit 1; }
[[ -f docs/contracts/SPEC-0097-hub-2-api-frontend-map.md ]] || { echo "missing map generated by hub task-pack"; exit 1; }

PATH="$mock_bin:/usr/bin:/bin" CHANGED_FILES=$'docs/status/current-task.md' \
  bash .agents/skills/vibe-hub/scripts/run.sh gates > "$tmp_dir/gates.out"
assert_has_step_report "$tmp_dir/gates.out"
grep -q 'STEP_ID: gates-summary' "$tmp_dir/gates.out" || { echo "gates summary step-report missing"; exit 1; }

PATH="$mock_bin:/usr/bin:/bin" CHANGED_FILES=$'docs/status/current-task.md' \
  bash .agents/skills/vibe-hub/scripts/run.sh full-loop \
  --spec-id SPEC-0097-hub-2 \
  --task-type feature \
  --current-role Dev \
  --next-role QA \
  --work-type full > "$tmp_dir/full-loop.out"
assert_has_step_report "$tmp_dir/full-loop.out"

popd >/dev/null

echo "test_skill_hub.sh passed"
